FROM nginx:latest

COPY build/index.html /usr/share/nginx/html/index.html
COPY build/congratulations.js /usr/share/nginx/html/congratulations.js
COPY build/999999th-visitor-you-won.gif /usr/share/nginx/html/999999th-visitor-you-won.gif
